### ISSUE TITLE
MultiVariantViewer with INDELs?

### ISSUE THREAD

**Issue by srobb1** [elsiklab/multivariantviewer#11]
Hi Colin,

Does this plugin work with INDELs? I tried with a vcf of indels and no data points are showing up.

Thanks,
Sofia

**Comment by cmdcolin** [comment]
By default no. It actually has a check for whether it is SNV with the assumption being that overlapping variants won't get drawn properly. I think adding indels would be fine beside that and you could comment out the check in js/View/FeatureGlyph/Variant.js

**Comment by srobb1** [comment]
Great! That works wonderfully! I will watch for overlapping variants.

**Comment by cmdcolin** [comment]
I made an option called includeIndels so that it allows you to render things basically that aren't SNVs, on master :)
