### ISSUE TITLE
Tracks overlap when there is no data

### ISSUE THREAD

**Issue by srobb1** [elsiklab/multivariantviewer#12]
Hi Colin,

When using the grid layout for variants where there is no variant data the Sample labels that are displayed on the left do not disappear or collapse. This causes other tracks to overlap with the grid track and it looks bad. Is there a way to make the sample names disappear or collapse when there is no data?

Thanks,
Sofia

<img width="638" alt="screen shot 2017-03-01 at 3 29 55 pm" src="https://cloud.githubusercontent.com/assets/1072991/23482287/1c78621a-fe94-11e6-97d4-3544ead80683.png">

**Comment by cmdcolin** [comment]
I can confirm. I guess you can do one of two things, either just make all the sublabels go away or try to actually make the empty track still as tall as usual

**Comment by srobb1** [comment]
How do I make the sublabels go away when there is no data?

**Comment by cmdcolin** [comment]
Both way probably need a bug fix to make it work, I guess it was just a question of which is better!

**Comment by srobb1** [comment]
I think I am leaning towards making the labels go away. Seems like a waste
of space if there are no variants to  have that big space with nothing,
especially if you have other tracks.

**Comment by srobb1** [comment]
I was trying to resolve this, but I am having no luck. I tried this:

`
   "showLabels" : "function(feat){if (feat === null  || feat  === undefined  ){ return false; }else{return true;}}",`


but I think it doesn't work because I don't know how to check to see if there is data in the current view.

**Comment by cmdcolin** [comment]
The showLabels configuration is actually for feature labels (like what would normally be displayed next to a feature to show the gene id)

I think it'll take a little work to get this issue fixed, I can try to help point you in right direction or take a look at it soon. sorry about delay

**Comment by srobb1** [comment]
I was just trying to see if I could do some of this on my own. So much of
the JBrowse code is a mystery to me. I was so good at GBrowse and so in the
dark with JBrowse.

When I set showLabels to false, the labels with the individual sample names
on the left disappear. So I thought I could write a call back, check for
data in the view and set to true or false accordingly.

**Comment by cmdcolin** [comment]
Ooo that is true, you can toggle that with showLabels and that is a custom feature of this plugin (there is the style->showLabels in normal jbrowse tracks but it is not related)

Unfortunately the showLabels for this plugin doesnt use callbacks!

**Comment by cmdcolin** [comment]
I went and added an alternative approach that may help. I think that it might be better in this case to always make the track height tall and render the subtracks always even if there are no variants to render. It seemed like it might be overly complicated and cause confusion to try to make the subtrack labels go away

Feel free to pull from github and try it out :)

**Comment by cmdcolin** [comment]
Also, I don't know if it helps but understanding the whole thing about what "define" (asynchronous module definition) and "declare" (dojo method to make classes) are helps to understand the jbrowse code

Since these two functions are basically the pre-amble to all the jbrowse files, it was important for me to understand the general idea behind those. Basically "define" declares your dependencies, and then "declare" makes a class like an object oriented classes, which can include inheritance or multiple inheritance. 

![](https://cloud.githubusercontent.com/assets/6511937/5888919/fbf4c9e0-a3d5-11e4-9558-0ffeaf7b7892.PNG)

Anyways that was one of the concepts that helped me understand jbrowse code better :)

The jbrowse code is very sparse on comments and api docs but I think the code is pretty readable if you can get past that >_<

**Comment by srobb1** [comment]
Uh Oh. Is there an option to select so that the tracks stay tall? Is there a option to select the track height. My tracks are overlapping even with data.

![screen shot 2017-03-08 at 10 21 32 am](https://cloud.githubusercontent.com/assets/1072991/23715224/25d33da8-03e9-11e7-820c-6a26351c28ad.png)

**Comment by cmdcolin** [comment]
woops, maybe try checking now, it changed the method of setting track height and had it calculated wrong

**Comment by srobb1** [comment]
Ahhh, so much better!! It looks great!

And thanks for the info above about define and declare. It does helps to demystify the code a bit. I wish I had a big block of time to sit down and work it out, I know I can. But I have so much other stuff to do. I will get it, it just will be little bit by little bit. Working with this plugin has helped me A LOT with understanding callbacks. How do you find out if a option allows callbacks and what arguments they take?

**Comment by cmdcolin** [comment]
There is not really a general rule about how to tell which configs take callbacks actually..it is sort of hard to tell which ones do!

It might be easier to tell which ones don't take callbacks

If you search the code for the config variable name, and it looks like the code is simply accessing a value like "this.config.someConfig" directly like this, then it is likely that it is not evaluating that config as a callback.

It has to do a couple different steps to make the callback functions execute

In any case, this would be a place where better documentation would help

**Comment by srobb1** [comment]
Thanks Colin!
