### ISSUE TITLE
config bug

### ISSUE THREAD

**Issue by colindaven** [elsiklab/multivariantviewer#13]
Hi,

there is a small config bug in the example config:

The showLabels line is missing a ":"

{
    "type": "MultiVariantViewer/View/Track/Grid",
    "urlTemplate": "variants.vcf.gz",
    "label": "Variant track",
    "storeClass": "JBrowse/Store/SeqFeature/VCFTabix",
    "showLabels" true
}

Best wishes,
Colin

**Comment by cmdcolin** [comment]
indeeed, thanks!
