### ISSUE TITLE
No call samples colored as homozygous ref 

### ISSUE THREAD

**Issue by carrere** [elsiklab/multivariantviewer#17]
Bonjour,

I just noticed that no-call samples (GT = ./.) are displayed in gray like homozygous reference samples.
I do not know if it is related to an issue I just submitted to JBrowse (https://github.com/GMOD/jbrowse/issues/980) but it seems that ./. are mis-evaluated.

Thanks for your help and your amazing job !

Sebastien

**Comment by cmdcolin** [comment]
I thought that no call did mean reference allele? Should they have their own color? Do you know how igv displays them?

**Comment by cmdcolin** [comment]
Cute doggy Avatar also:)

**Comment by carrere** [comment]
No call means noData/notEnoughData to perform a call in this region. It is
really different from 0/0 that means that read alignement confirm this
region is the same as the reference.
I would suggest to use the same color as the background to emulate
transparency, so #fff for default jbrowse theme.
I do not know how it is displayed in IGV (I'm a Jbrowse fan !).

Seb

Le 7 févr. 2018 6:29 PM, "Colin Diesh" <notifications@github.com> a écrit :

I thought that no call did mean reference allele? Should they have their
own color? So you know how igv displays them?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elsiklab/multivariantviewer/issues/17#issuecomment-363846039>,
or mute the thread

**Comment by carrere** [comment]
A "grand bleu de Gascogne", not the smartest dog in the world but nice and
funny !

**Comment by srobb1** [comment]
Hi Colin,
I agree with Sebastien. Making it so we can select the color of no calls or having an option to make them transparent would be super great and helpful.

Sofia

**Comment by cmdcolin** [comment]
Looks like with IGV these NO_CALL are marked as white instead of grey. I had imagined that no call was sort of equivalent to reference but I guess it is separate :)

**Comment by carrere** [comment]
From https://samtools.github.io/hts-specs/VCFv4.3.pdf :

> GT (String): Genotype, encoded as allele values separated by either of / or |. The allele values are 0 for the
reference allele (what is in the REF field), 1 for the first allele listed in ALT, 2 for the second allele list in
ALT and so on. For diploid calls examples could be 0/1, 1 | 0, or 1/2, etc. Haploid calls, e.g. on Y, male
non-pseudoautosomal X, or mitochondrion, are indicated by having only one allele value. A triploid call might
look like 0/0/1. **If a call cannot be made for a sample at a given locus, ‘.’ must be specified for each missing
allele in the GT field (for example ‘./.’ for a diploid genotype and ‘.’ for haploid genotype).**

**Comment by cmdcolin** [comment]
Should be fixed now...no_call is specified as white

**Comment by cmdcolin** [comment]
Pushed a new version to github and it also allows "sublabel" configs to be specified via CSV :)

See config sublabelsCsv

**Comment by cmdcolin** [comment]
Let me know if there are any other issues. Thanks for the tips on making this correct

**Comment by carrere** [comment]
@cmdcolin "no_call" rendering works perfect on my data ! Thanks again Colin !

**Comment by srobb1** [comment]
Thank you @cmdcolin! It works great!!

On Mon, Feb 12, 2018 at 3:10 AM, Sebastien Carrere <notifications@github.com
