### ISSUE TITLE
LDTrack show an error

### ISSUE THREAD

**Issue by shenweima** [elsiklab/multivariantviewer#19]
LDTrack show an error, but Grid and Matrix is normal.
Diagnostic message is:
Unable to load undefinde?

**Comment by cmdcolin** [comment]
Are you running the node js linkage_server? It is necessary for the LDTrack

**Comment by cmdcolin** [comment]
Any updates?

**Comment by shenweima** [comment]
Yes, Thank you very much

**Comment by cmdcolin** [comment]
It did work? Very cool :) feel free to repost if there are any issues
