### ISSUE TITLE
Grid track not displayed on Jbrowse version 1.16.1

### ISSUE THREAD

**Issue by dionnezaal** [elsiklab/multivariantviewer#20]
An error occurs when trying to load a `MultiVariantViewer/View/Track/Grid` track:

![screenshot 2019-01-16 at 16 54 53](https://user-images.githubusercontent.com/1343609/51261852-63749000-19b1-11e9-9d2c-3ad32dfb514a.png)

Probably due to new VCF header parsing with @gmod/vcf? Same track works with Jbrowse version 1.15.4.

**Comment by cmdcolin** [comment]
Thanks so much for catching this. The @gmod/vcf update was the case.

I pushed a change to this plugin "version 1.0.3" that should work with the newest version and be backwards compatible too

**Comment by dionnezaal** [comment]
Thank you for fixing this so quickly! It works fine again in version 1.16.1.
