### ISSUE TITLE
LDtrack shows error (invalid start and end coordinates)

### ISSUE THREAD

**Issue by romens96** [elsiklab/multivariantviewer#21]
When running ldtrack I got an error when displaying the track .
(Error: invalid start and end coordinates. must be provided, start must be less than or equal to end).

From what I checked in the example vcf files (volvox), there is only position column but not start and stop column.
And from my understanding, only a position column is available in vcf files.
Anyone had this error and solved it?

P.S I am new to this

**Comment by cmdcolin** [comment]
I believe there are some issues with the latest version of JBrowse that have not been fixed for both the Matrix and LDTrack types

I can update you when these become fixed

**Comment by cmdcolin** [comment]
By Latest version of JBrowse I mean anything after 1.16.0 version. You could try an earlier version to test also

**Comment by cmdcolin** [comment]
Ok, the code should be updated on this repo to work better with JBrowse 1.16.0+. Pull from master or get the latest version from the releases page :)

**Comment by cmdcolin** [comment]
Let me know if there are any issues

**Comment by romens96** [comment]
> Let me know if there are any issues

@cmdcolin Thank you for your quick assistance. Really appreciate it.
Will let you know if there are still issues.
Thanks again!

**Comment by romens96** [comment]
@cmdcolin 
I am still having trouble in displaying the ldtrack after the installing the latest release that you have uploaded few hours ago.
The same error came out
(Error: invalid start and end coordinates. must be provided, start must be less than or equal to end)
