### ISSUE TITLE
LDserver issue

### ISSUE THREAD

**Issue by romens96** [elsiklab/multivariantviewer#22]
![image](https://user-images.githubusercontent.com/49174422/55467060-0e9cf900-5633-11e9-9cf6-b20edf2f6182.png)

I don't quite understand about reversing the proxy onto port 80.
I am serving the browser to the public.
Does it mean that I have to change ldserver=http://localhost:4730/ to my ip?

**Comment by cmdcolin** [comment]
This is a hard question to answer succinctly, because it depends on your setup. You should lookup how to deploy a node.js/express.js microservice. Then yes, you simply change the localhost:4730 into something that can be accessible to the public e.g. your ip or hostname.

**Comment by cmdcolin** [comment]
The reverse proxying can be used to make it so that a request to

http://yoursite/nodejsservice get's proxied internally to the localhost:4730

**Comment by romens96** [comment]
Thanks for clarifying about the ldserver issue.

I have another issue is that when I enable my LDmatrix plugin, it gives an error of (this. is not defined).

I am using Browse version 1.16.3 and the latest multivariantviewer repo which you have updated 2 days ago.

**Comment by cmdcolin** [comment]
I found a couple bugs and pushed some new changes to the master branch.

Can you retry with those?

**Comment by cmdcolin** [comment]
If you still see an error can you look at the javascript console and report the full stack trace

**Comment by romens96** [comment]
Thank you.
Will report the full stack trace if I found any error.
