### ISSUE TITLE
BCF instead of vcf.gz

### ISSUE THREAD

**Issue by Bjoernsen** [elsiklab/multivariantviewer#24]
Is there a way to extent this plugin to use `BCF` (and `.csi`) instead of `vcf.gz` files?

**Comment by cmdcolin** [comment]
You can use the csi index with vcf.gz but there is no bcf support in jbrowse itself. I'd recommend making an issue on the jbrowse github if you need bcf support. But if you just need to use csi for instance with large genomes you can use vcf.gz with csi

**Comment by Bjoernsen** [comment]
ok, thank you!
