### ISSUE TITLE
TooltipDialog.js not found

### ISSUE THREAD

**Issue by carrere** [elsiklab/multivariantviewer#7]
Bonjour,

When I try to display a track with "MultiVariantViewer/View/Track/Grid" class, I've got the following error in the console and nothing is displayed:

NetworkError: 404 Not Found  http://localhost/web/jbrowse/src/dijit/TooltipDialog.js

I use the master branch of **multivariantviewer** and the official release of **JBrowse (1.12.1)**

And TooltipDialog.js is not in this release of JBrowse. 

Sebastien

**Comment by cmdcolin** [comment]
Thanks for raising the issue. I just pushed to master a fix, you should be able to pull and re-run. I had added the dijit/TooltipDialog class for some extra feature, but it is not included in the JBrowse official releases so it is just using normal dijit/Tooltip now

See if pulling from master fixes it!

**Comment by carrere** [comment]
Yes it works !
Thanks

**Comment by cmdcolin** [comment]
👍
