### ISSUE TITLE
how to show sublabels array

### ISSUE THREAD

**Issue by srobb1** [elsiklab/multivariantviewer#9]
Hi,

What do I need to add to show the sublabels array? These are supposed to be in the same balloon as the sample name? 

Here is what I have in my tracksList.json. Nothing but the sample name shows up. 

{
    "type": "MultiVariantViewer/View/Track/Grid",
     "urlTemplate"   : "../files/recessive_eye_strict_SNPs_ann.vcf.gz",
    "label": "Variant track",
    "storeClass": "JBrowse/Store/SeqFeature/VCFTabix",
    "showLabels" : true,
    "showTooltips" : true,
    "sublabels" :  [{"name": "sample1", "color": "red", "description": "Optional description or sample displayed on mouseover", "population": "CEU"}],
      "metadata": {"legend": "cyan is heterozygous non-ref, grey homozygous ref, blue is homozygous non-ref"}
}

Also,
Is anything supposed to appear when you hoover or click the actual SNP glyph? Is there something like fmtDetailValue_ I can call to format a description when hovering over one sample's SNP?

Thanks!
Sofia

**Comment by cmdcolin** [comment]
Hmm I guess the main functionality is listing the sublabel on the left of screen as a "subtrack"

There is nothing that appears during hover. That would be a great feature to add though.

I didn't exactly get the error that you were seeing though but it does sort of try to match the sublabel array to sample names found in vcf.

Check the test data by loading ?data=plugins/MultiVariantViewer/test/data too!

**Comment by srobb1** [comment]
Hi Colin,
I tried to load the example data but I get this error:

Cannot use 'in' operator to search for 'name' in MultiVariantViewer


The labels that appear on the left are so short, the text gets cut off, I
cannot even read the name of the sample. If the sublabels are below the
name, no wonder I can't see them :/

Sofia

**Comment by cmdcolin** [comment]
Hmm if there is a javascript error that might affect a bunch of layout stuff that affects everything downstream, so that could be the problem with the labels.

You can manually set "labelWidth" parameter to expand labels too if that is true, but I suspect the javascript error needs fixing

Was that on the "test data"? Chrome/firefox? Can you paste full error?

**Comment by srobb1** [comment]
I am using Chrome on a Mac. Here is the full error.

dojo.js:82 TypeError: Cannot use 'in' operator to search for 'name' in
MultiVariantViewer
    at Object.<anonymous> (dojo.js:30)
    at Object.<anonymous> (dojo.js:31)
    at Object._milestoneFunction (dojo.js:82)
    at Object.initPlugins (dojo.js:30)
    at dojo.js:28
    at b (dojo.js:235)
    at c (dojo.js:235)
    at k.resolve (dojo.js:237)
    at Object.<anonymous> (dojo.js:84)
    at dojo.js:140 "TypeError: Cannot use 'in' operator to search for
'name' in MultiVariantViewer
    at Object.<anonymous> (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:30:518)
    at Object.<anonymous> (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:31:42)
    at Object._milestoneFunction (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:82:339)
    at Object.initPlugins (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:30:334)
    at https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:28:17
    at b (https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:235:106)
    at c (https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:235:32)
    at k.resolve (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:237:123)
    at Object.<anonymous> (
https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:84:421)
    at https://genomesdev.stowers.org/jbrowse/src/dojo/dojo.js:140:498"

**Comment by cmdcolin** [comment]
That is actually an error I know about >_<

basically jbrowse gets mad if you include plugins in both jbrowse.conf and trackList.json

there is a pull request that needs to be made to jbrowse proper to get that fixed, in meantime you can uncomment the plugins section in the trackList.json and include it in jbrowse.conf manually.

**Comment by cmdcolin** [comment]
Er sorry not uncomment but remove the plugins section in the trackList.json for MultiVariantViewer

**Comment by srobb1** [comment]
That worked! See the example helped a lot!!

I changed the height that worked too. Not sure what I tried before when it didn't work. 

Thanks for the help!
Sofia

**Comment by cmdcolin** [comment]
Cool, feel free to reopen if you find issues!

**Comment by cmdcolin** [comment]
New version on master branch now so things like height: 12 is default, easier to change colors, etc.
